"""
Base Agent - Abstract base class for all agents in the system
"""
from abc import ABC, abstractmethod
from typing import Dict, Any, List
from datetime import datetime


class BaseAgent(ABC):
    """
    Abstract base class for all agents in the Campus Incident Report Analysis System
    
    Provides common functionality including:
    - Agent identification and metadata
    - Execution logging
    - Error handling patterns
    - Status tracking
    """
    
    def __init__(self, name: str, description: str):
        self.name = name
        self.description = description
        self.created_at = datetime.now()
        self.execution_history: List[Dict[str, Any]] = []
        self.status = "initialized"
    
    @abstractmethod
    def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the agent's primary function
        
        Args:
            input_data: Input data specific to the agent
        
        Returns:
            Dict containing execution results and status
        """
        pass
    
    def log_execution(self, input_data: Dict[str, Any], 
                     output_data: Dict[str, Any], 
                     status: str) -> None:
        """
        Log execution details for audit and debugging
        
        Args:
            input_data: Input provided to the agent
            output_data: Output generated by the agent
            status: Execution status (success, error, warning)
        """
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "agent_name": self.name,
            "status": status,
            "input_summary": self._summarize_input(input_data),
            "output_summary": self._summarize_output(output_data),
            "execution_time": datetime.now().isoformat()
        }
        
        self.execution_history.append(log_entry)
        self.status = status
    
    def _summarize_input(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create a summary of input data for logging
        
        Args:
            input_data: Input data to summarize
        
        Returns:
            Summarized input data
        """
        summary = {}
        
        for key, value in input_data.items():
            if isinstance(value, str):
                # Truncate long strings
                summary[key] = value[:100] + "..." if len(value) > 100 else value
            elif isinstance(value, (list, dict)):
                # Count items in collections
                summary[key] = f"{type(value).__name__} with {len(value)} items"
            else:
                summary[key] = str(value)
        
        return summary
    
    def _summarize_output(self, output_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create a summary of output data for logging
        
        Args:
            output_data: Output data to summarize
        
        Returns:
            Summarized output data
        """
        summary = {}
        
        # Always include status
        summary["status"] = output_data.get("status", "unknown")
        
        # Include key metrics if available
        if "overall_score" in output_data:
            summary["overall_score"] = output_data["overall_score"]
        
        if "validation_result" in output_data:
            summary["validation_result"] = output_data["validation_result"]
        
        if "execution_summary" in output_data:
            exec_summary = output_data["execution_summary"]
            summary["execution_summary"] = {
                "status": exec_summary.get("overall_status", "unknown"),
                "actions": exec_summary.get("immediate_actions_executed", 0)
            }
        
        # Count collections
        for key, value in output_data.items():
            if isinstance(value, list) and key not in summary:
                summary[f"{key}_count"] = len(value)
        
        return summary
    
    def get_status(self) -> Dict[str, Any]:
        """
        Get current agent status and metadata
        
        Returns:
            Dict containing agent status information
        """
        return {
            "name": self.name,
            "description": self.description,
            "status": self.status,
            "created_at": self.created_at.isoformat(),
            "executions_count": len(self.execution_history),
            "last_execution": self.execution_history[-1]["timestamp"] if self.execution_history else None
        }
    
    def get_execution_history(self, limit: int = 10) -> List[Dict[str, Any]]:
        """
        Get recent execution history
        
        Args:
            limit: Maximum number of entries to return
        
        Returns:
            List of recent execution log entries
        """
        return self.execution_history[-limit:] if self.execution_history else []
    
    def validate_input(self, input_data: Dict[str, Any], 
                      required_fields: List[str]) -> Dict[str, Any]:
        """
        Validate input data contains required fields
        
        Args:
            input_data: Input data to validate
            required_fields: List of required field names
        
        Returns:
            Dict with validation results
        """
        missing_fields = []
        
        for field in required_fields:
            if field not in input_data or input_data[field] is None:
                missing_fields.append(field)
        
        return {
            "valid": len(missing_fields) == 0,
            "missing_fields": missing_fields,
            "provided_fields": list(input_data.keys())
        }
    
    def handle_error(self, error: Exception, context: str = "") -> Dict[str, Any]:
        """
        Standard error handling for agents
        
        Args:
            error: Exception that occurred
            context: Additional context about the error
        
        Returns:
            Standardized error response
        """
        error_response = {
            "status": "error",
            "error": str(error),
            "error_type": type(error).__name__,
            "agent": self.name,
            "context": context,
            "timestamp": datetime.now().isoformat()
        }
        
        self.log_execution({}, error_response, "error")
        return error_response
    
    def create_success_response(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create standardized success response
        
        Args:
            data: Response data
        
        Returns:
            Standardized success response
        """
        response = {
            "status": "success",
            "timestamp": datetime.now().isoformat(),
            "agent": self.name,
            **data
        }
        
        return response
    
    def __str__(self) -> str:
        """String representation of the agent"""
        return f"{self.name} ({self.status})"
    
    def __repr__(self) -> str:
        """Detailed string representation of the agent"""
        return f"<{self.__class__.__name__}: {self.name}, status={self.status}, executions={len(self.execution_history)}>"